var namespace_general_health_care_elements_1_1_control_units =
[
    [ "ControlUnitHealthCare", "class_general_health_care_elements_1_1_control_units_1_1_control_unit_health_care.html", "class_general_health_care_elements_1_1_control_units_1_1_control_unit_health_care" ],
    [ "ControlUnitHealthCareDepartment", "class_general_health_care_elements_1_1_control_units_1_1_control_unit_health_care_department.html", "class_general_health_care_elements_1_1_control_units_1_1_control_unit_health_care_department" ],
    [ "ControlUnitOrganizationalUnit", "class_general_health_care_elements_1_1_control_units_1_1_control_unit_organizational_unit.html", "class_general_health_care_elements_1_1_control_units_1_1_control_unit_organizational_unit" ]
];