var namespace_general_health_care_elements_1_1_department_models_1_1_emergency =
[
    [ "ControlUnitEmergency", "class_general_health_care_elements_1_1_department_models_1_1_emergency_1_1_control_unit_emergency.html", "class_general_health_care_elements_1_1_department_models_1_1_emergency_1_1_control_unit_emergency" ],
    [ "EmergencyPatientPath", "class_general_health_care_elements_1_1_department_models_1_1_emergency_1_1_emergency_patient_path.html", "class_general_health_care_elements_1_1_department_models_1_1_emergency_1_1_emergency_patient_path" ],
    [ "EventEmergencyPatientArrival", "class_general_health_care_elements_1_1_department_models_1_1_emergency_1_1_event_emergency_patient_arrival.html", "class_general_health_care_elements_1_1_department_models_1_1_emergency_1_1_event_emergency_patient_arrival" ],
    [ "EventEmergencyPatientLeave", "class_general_health_care_elements_1_1_department_models_1_1_emergency_1_1_event_emergency_patient_leave.html", "class_general_health_care_elements_1_1_department_models_1_1_emergency_1_1_event_emergency_patient_leave" ],
    [ "IInputEmergency", "interface_general_health_care_elements_1_1_department_models_1_1_emergency_1_1_i_input_emergency.html", "interface_general_health_care_elements_1_1_department_models_1_1_emergency_1_1_i_input_emergency" ],
    [ "RequestEmergencyAction", "class_general_health_care_elements_1_1_department_models_1_1_emergency_1_1_request_emergency_action.html", "class_general_health_care_elements_1_1_department_models_1_1_emergency_1_1_request_emergency_action" ]
];