var namespace_general_health_elements_1_1_inpatient_1_1_control_units =
[
    [ "ControlUnitInpatientDetailed", "class_general_health_elements_1_1_inpatient_1_1_control_units_1_1_control_unit_inpatient_detailed.html", "class_general_health_elements_1_1_inpatient_1_1_control_units_1_1_control_unit_inpatient_detailed" ]
];