var namespace_general_health_care_elements_1_1_special_facility =
[
    [ "ControlUnitSpecialServiceModel", "class_general_health_care_elements_1_1_special_facility_1_1_control_unit_special_service_model.html", "class_general_health_care_elements_1_1_special_facility_1_1_control_unit_special_service_model" ],
    [ "DelegateAvailabilitiesForRequest", "class_general_health_care_elements_1_1_special_facility_1_1_delegate_availabilities_for_request.html", "class_general_health_care_elements_1_1_special_facility_1_1_delegate_availabilities_for_request" ],
    [ "EventBookingSpecialServiceDue", "class_general_health_care_elements_1_1_special_facility_1_1_event_booking_special_service_due.html", "class_general_health_care_elements_1_1_special_facility_1_1_event_booking_special_service_due" ],
    [ "EventSpecialFacilityPatientArrival", "class_general_health_care_elements_1_1_special_facility_1_1_event_special_facility_patient_arrival.html", "class_general_health_care_elements_1_1_special_facility_1_1_event_special_facility_patient_arrival" ],
    [ "IInputSpecialFacility", "interface_general_health_care_elements_1_1_special_facility_1_1_i_input_special_facility.html", "interface_general_health_care_elements_1_1_special_facility_1_1_i_input_special_facility" ],
    [ "RequestSpecialFacilitiyService", "class_general_health_care_elements_1_1_special_facility_1_1_request_special_facilitiy_service.html", "class_general_health_care_elements_1_1_special_facility_1_1_request_special_facilitiy_service" ],
    [ "RequestSpecialFacilityAction", "class_general_health_care_elements_1_1_special_facility_1_1_request_special_facility_action.html", "class_general_health_care_elements_1_1_special_facility_1_1_request_special_facility_action" ],
    [ "SpecialServicePatientPath", "class_general_health_care_elements_1_1_special_facility_1_1_special_service_patient_path.html", "class_general_health_care_elements_1_1_special_facility_1_1_special_service_patient_path" ]
];