var namespace_sample_hospital_model_1_1_visualization =
[
    [ "WPFVisualizationEngineHealthCareDepartmentControlUnit", "class_sample_hospital_model_1_1_visualization_1_1_w_p_f_visualization_engine_health_care_department_control_unit.html", "class_sample_hospital_model_1_1_visualization_1_1_w_p_f_visualization_engine_health_care_department_control_unit" ],
    [ "WPFVisualizationEngineOutpatientDepartment", "class_sample_hospital_model_1_1_visualization_1_1_w_p_f_visualization_engine_outpatient_department.html", "class_sample_hospital_model_1_1_visualization_1_1_w_p_f_visualization_engine_outpatient_department" ],
    [ "WPFVisualizationHealthCareOrganizationalUnit", "class_sample_hospital_model_1_1_visualization_1_1_w_p_f_visualization_health_care_organizational_unit.html", "class_sample_hospital_model_1_1_visualization_1_1_w_p_f_visualization_health_care_organizational_unit" ]
];