var namespace_general_health_care_elements_1_1_treatment_admission_types =
[
    [ "Admission", "class_general_health_care_elements_1_1_treatment_admission_types_1_1_admission.html", "class_general_health_care_elements_1_1_treatment_admission_types_1_1_admission" ],
    [ "AdmissionType", "class_general_health_care_elements_1_1_treatment_admission_types_1_1_admission_type.html", "class_general_health_care_elements_1_1_treatment_admission_types_1_1_admission_type" ],
    [ "InpatientAdmissionTypes", "class_general_health_care_elements_1_1_treatment_admission_types_1_1_inpatient_admission_types.html", "class_general_health_care_elements_1_1_treatment_admission_types_1_1_inpatient_admission_types" ],
    [ "InpatientTreatmentTypes", "class_general_health_care_elements_1_1_treatment_admission_types_1_1_inpatient_treatment_types.html", "class_general_health_care_elements_1_1_treatment_admission_types_1_1_inpatient_treatment_types" ],
    [ "OutpatientAdmissionTypes", "class_general_health_care_elements_1_1_treatment_admission_types_1_1_outpatient_admission_types.html", "class_general_health_care_elements_1_1_treatment_admission_types_1_1_outpatient_admission_types" ],
    [ "SpecialServiceAdmissionTypes", "class_general_health_care_elements_1_1_treatment_admission_types_1_1_special_service_admission_types.html", "class_general_health_care_elements_1_1_treatment_admission_types_1_1_special_service_admission_types" ],
    [ "TreatmentType", "class_general_health_care_elements_1_1_treatment_admission_types_1_1_treatment_type.html", "class_general_health_care_elements_1_1_treatment_admission_types_1_1_treatment_type" ]
];