var namespace_general_health_care_elements_1_1_booking_models =
[
    [ "EntityMultipleBookingWaitingListSchedule", "class_general_health_care_elements_1_1_booking_models_1_1_entity_multiple_booking_waiting_list_schedule.html", "class_general_health_care_elements_1_1_booking_models_1_1_entity_multiple_booking_waiting_list_schedule" ],
    [ "EntitySingleBookingModelWaitingList", "class_general_health_care_elements_1_1_booking_models_1_1_entity_single_booking_model_waiting_list.html", "class_general_health_care_elements_1_1_booking_models_1_1_entity_single_booking_model_waiting_list" ],
    [ "EntityWaitingListSchedule", "class_general_health_care_elements_1_1_booking_models_1_1_entity_waiting_list_schedule.html", "class_general_health_care_elements_1_1_booking_models_1_1_entity_waiting_list_schedule" ],
    [ "GeneralBookingModel", "class_general_health_care_elements_1_1_booking_models_1_1_general_booking_model.html", "class_general_health_care_elements_1_1_booking_models_1_1_general_booking_model" ],
    [ "IBookingModel", "interface_general_health_care_elements_1_1_booking_models_1_1_i_booking_model.html", "interface_general_health_care_elements_1_1_booking_models_1_1_i_booking_model" ],
    [ "ImmediateBookingModel", "class_general_health_care_elements_1_1_booking_models_1_1_immediate_booking_model.html", "class_general_health_care_elements_1_1_booking_models_1_1_immediate_booking_model" ],
    [ "ITimeLineConfiguration", "interface_general_health_care_elements_1_1_booking_models_1_1_i_time_line_configuration.html", "interface_general_health_care_elements_1_1_booking_models_1_1_i_time_line_configuration" ],
    [ "PerWeekdayTimeLineConfiguration", "class_general_health_care_elements_1_1_booking_models_1_1_per_weekday_time_line_configuration.html", "class_general_health_care_elements_1_1_booking_models_1_1_per_weekday_time_line_configuration" ],
    [ "SinglePerDayTimeLine", "class_general_health_care_elements_1_1_booking_models_1_1_single_per_day_time_line.html", "class_general_health_care_elements_1_1_booking_models_1_1_single_per_day_time_line" ],
    [ "Slot", "class_general_health_care_elements_1_1_booking_models_1_1_slot.html", "class_general_health_care_elements_1_1_booking_models_1_1_slot" ],
    [ "SlotRequest", "class_general_health_care_elements_1_1_booking_models_1_1_slot_request.html", "class_general_health_care_elements_1_1_booking_models_1_1_slot_request" ],
    [ "TimeAtom", "class_general_health_care_elements_1_1_booking_models_1_1_time_atom.html", "class_general_health_care_elements_1_1_booking_models_1_1_time_atom" ],
    [ "TimeAtomConfig", "class_general_health_care_elements_1_1_booking_models_1_1_time_atom_config.html", "class_general_health_care_elements_1_1_booking_models_1_1_time_atom_config" ],
    [ "TimeAtomStartEndIncrementConfig", "class_general_health_care_elements_1_1_booking_models_1_1_time_atom_start_end_increment_config.html", "class_general_health_care_elements_1_1_booking_models_1_1_time_atom_start_end_increment_config" ]
];